// <auto-generated />
using System;
using DirectoryOfPeople.Repositori;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DirectoryOfPeople.Repositori.Migrations
{
    [DbContext(typeof(DirectoryOfPeopleDbContext))]
    partial class DirectoryOfPeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DirectoryOfPeople.DTO.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DirectoryOfPeople.DTO.ContactInformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ContactNamber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(0)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("ContactInformation");
                });

            modelBuilder.Entity("DirectoryOfPeople.DTO.Person", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(0)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PictureAddres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DirectoryOfPeople.DTO.PersonalityConnection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(0)");

                    b.HasKey("ID");

                    b.ToTable("PersonalityConnections");
                });

            modelBuilder.Entity("FromPeopelPersonalityConnection", b =>
                {
                    b.Property<int>("FromPersonID")
                        .HasColumnType("int");

                    b.Property<int>("FromPersonalityConnectionID")
                        .HasColumnType("int");

                    b.HasKey("FromPersonID", "FromPersonalityConnectionID");

                    b.HasIndex("FromPersonalityConnectionID");

                    b.ToTable("FromPeopelPersonalityConnection");
                });

            modelBuilder.Entity("ToPersonalityConnectionPerson", b =>
                {
                    b.Property<int>("ToPersonID")
                        .HasColumnType("int");

                    b.Property<int>("ToPersonalityConnectionID")
                        .HasColumnType("int");

                    b.HasKey("ToPersonID", "ToPersonalityConnectionID");

                    b.HasIndex("ToPersonalityConnectionID");

                    b.ToTable("ToPersonalityConnectionPerson");
                });

            modelBuilder.Entity("DirectoryOfPeople.DTO.ContactInformation", b =>
                {
                    b.HasOne("DirectoryOfPeople.DTO.Person", "Person")
                        .WithMany("ContactInformation")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DirectoryOfPeople.DTO.Person", b =>
                {
                    b.HasOne("DirectoryOfPeople.DTO.City", "City")
                        .WithMany("Persons")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("FromPeopelPersonalityConnection", b =>
                {
                    b.HasOne("DirectoryOfPeople.DTO.Person", null)
                        .WithMany()
                        .HasForeignKey("FromPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryOfPeople.DTO.PersonalityConnection", null)
                        .WithMany()
                        .HasForeignKey("FromPersonalityConnectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToPersonalityConnectionPerson", b =>
                {
                    b.HasOne("DirectoryOfPeople.DTO.Person", null)
                        .WithMany()
                        .HasForeignKey("ToPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryOfPeople.DTO.PersonalityConnection", null)
                        .WithMany()
                        .HasForeignKey("ToPersonalityConnectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectoryOfPeople.DTO.City", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("DirectoryOfPeople.DTO.Person", b =>
                {
                    b.Navigation("ContactInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
